const AppData = {
  // BASE_URL: 'https://newstg1-bus.kupos.cl/',
  BASE_URL: 'https://newstg2-bus.kupos.cl/',
  // BASE_URL: 'https://newstg2-bebus.kupos.cl/',
  // BASE_URL: 'https://api.pasajebus.com/',
  // BASE_URL: 'https://pbstage.kupas.cl/',
  CARPOOL_URL: '',
  // AT_URL: 'https://at.kupos.cl/',
  AT_URL: 'https://newstg2-at.kupos.cl/',
  // AT_URL: 'https://stg.at.kupos.cl/',
  // AT_URL: 'https://at.kupos.cl/',
  // AT_URL: 'http://3.81.28.102:4000/',
  // BASE_URL: 'https://www.portals.org.in/',
  // BASE_URL: 'https://api.pasajebus.com/',
  BASE_URL_V2: 'https://stg2.at.kupos.cl/api/v2/',
  BASE_URL_V3: 'https://stg2.at.kupos.cl/api/v3/',
  BASE_URL_V4: 'https://stg2.at.kupos.cl/api/v4/',
  // AT_STG_1: 'http://3.236.96.9:4000/',
  // AT_STG_2: 'https://stg2.at.kupos.cl/',
  // BASE_URL_V3: 'https://at.kupos.cl/api/v3/',
  BIP_URL: 'https://stg2.bip.kupos.cl/',
  BIP_URL_V2: 'https://newstg2-bip.kupos.cl/',
  // BIP_URL: 'http://3.225.222.55:8000/',
  ONE_SIGNAL_APP_ID: '234fd2db-ea84-4b59-ab4b-28a3ea826474',
  SENDER_ID: '730867902568',
  MAP_API_KEY: 'AIzaSyATIgRwHXckoLpBJuf1E6yNGEmRmAsBYA4',
  FB_APP_ID: '409783556699660',
  // FB_APP_ID: '177184106959636',mjmmm
};
export default AppData;
